# Generated by Codex on 2026-08-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FlashcardProgress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("course_id", models.CharField(db_index=True, max_length=64)),
                ("card_key", models.CharField(max_length=64)),
                ("term", models.TextField(blank=True)),
                ("definition", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("mastered", "Mastered"), ("in_progress", "In Progress")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("starred", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flashcard_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="flashcardprogress",
            index=models.Index(fields=["course_id", "user"], name="agent_flash_course__700abd_idx"),
        ),
        migrations.AddConstraint(
            model_name="flashcardprogress",
            constraint=models.UniqueConstraint(
                fields=("course_id", "user", "card_key"),
                name="unique_flashcard_progress_per_user",
            ),
        ),
    ]
