# Generated by Codex on 2026-08-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0002_flashcardprogress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarSyncRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("course_id", models.CharField(db_index=True, max_length=64)),
                ("date", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=32)),
                ("google_event_id", models.CharField(max_length=255)),
                ("synced_at", models.CharField(max_length=64)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="calendar_sync_records", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="CourseSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("session_id", models.CharField(max_length=64, unique=True)),
                ("course_id", models.CharField(db_index=True, max_length=64)),
                ("created_at", models.CharField(max_length=64)),
                ("updated_at", models.CharField(max_length=64)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="course_sessions", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="CustomEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_id", models.CharField(max_length=64, unique=True)),
                ("course_id", models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ("date", models.CharField(max_length=10)),
                ("time", models.CharField(blank=True, max_length=5, null=True)),
                ("title", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=32)),
                ("synced", models.BooleanField(default=False)),
                ("google_event_id", models.CharField(blank=True, max_length=255, null=True)),
                ("synced_at", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.CharField(max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="custom_events", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="GradeItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("course_id", models.CharField(db_index=True, max_length=64)),
                ("item_id", models.CharField(max_length=64)),
                ("component", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("score", models.FloatField()),
                ("max_points", models.FloatField()),
                ("date", models.CharField(blank=True, max_length=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="grade_items", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="MasteryScore",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("course_id", models.CharField(db_index=True, max_length=64)),
                ("topic", models.CharField(max_length=255)),
                ("score", models.FloatField()),
                ("attempts", models.PositiveIntegerField()),
                ("last_seen", models.CharField(blank=True, max_length=64, null=True)),
                ("status", models.CharField(max_length=32)),
                ("rebuilt_at", models.CharField(max_length=64)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="mastery_scores", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("course_id", models.CharField(db_index=True, max_length=64)),
                ("lecture_id", models.CharField(max_length=64)),
                ("chunk_id", models.CharField(max_length=64)),
                ("topic", models.CharField(max_length=255)),
                ("question", models.TextField()),
                ("correct_answer", models.TextField()),
                ("user_answer", models.TextField()),
                ("correct", models.BooleanField()),
                ("timestamp", models.CharField(max_length=64)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="quiz_attempts", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="SessionMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(max_length=16)),
                ("content", models.TextField()),
                ("timestamp", models.CharField(max_length=64)),
                ("sources", models.JSONField(blank=True, default=list)),
                ("grounded", models.BooleanField(blank=True, null=True)),
                ("position", models.PositiveIntegerField()),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="agent.coursesession")),
            ],
            options={"ordering": ["position"]},
        ),
        migrations.AddIndex(model_name="calendarsyncrecord", index=models.Index(fields=["course_id", "user"], name="agent_calen_course__38e0d1_idx")),
        migrations.AddIndex(model_name="coursesession", index=models.Index(fields=["course_id", "user"], name="agent_cours_course__1e5f26_idx")),
        migrations.AddIndex(model_name="customevent", index=models.Index(fields=["user", "date"], name="agent_custo_user_id_994047_idx")),
        migrations.AddIndex(model_name="customevent", index=models.Index(fields=["course_id"], name="agent_custo_course__56006f_idx")),
        migrations.AddIndex(model_name="gradeitem", index=models.Index(fields=["course_id", "user"], name="agent_grade_course__481483_idx")),
        migrations.AddIndex(model_name="masteryscore", index=models.Index(fields=["course_id", "user", "score"], name="agent_maste_course__8da41a_idx")),
        migrations.AddIndex(model_name="quizattempt", index=models.Index(fields=["course_id", "user", "timestamp"], name="agent_quiza_course__f641e9_idx")),
        migrations.AddConstraint(model_name="gradeitem", constraint=models.UniqueConstraint(fields=("course_id", "user", "item_id"), name="unique_grade_item_per_user")),
        migrations.AddConstraint(model_name="masteryscore", constraint=models.UniqueConstraint(fields=("course_id", "user", "topic"), name="unique_mastery_score_per_user")),
        migrations.AddConstraint(model_name="sessionmessage", constraint=models.UniqueConstraint(fields=("session", "position"), name="unique_session_message_position")),
    ]
