# Generated by Django 6.1 on 2026-08-25 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_legacy_calendar_credentials(apps, schema_editor):
    GoogleAccount = apps.get_model("agent", "GoogleAccount")
    GoogleCalendarConnection = apps.get_model("agent", "GoogleCalendarConnection")
    for account in GoogleAccount.objects.exclude(refresh_token="").iterator():
        GoogleCalendarConnection.objects.update_or_create(
            user_id=account.user_id,
            defaults={
                "access_token": account.access_token,
                "refresh_token": account.refresh_token,
                "token_expiry": account.token_expiry,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_seed_computer_graphics_saved_site'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expiry', models.DateTimeField()),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(preserve_legacy_calendar_credentials, migrations.RunPython.noop),
        migrations.RemoveField(model_name='googleaccount', name='access_token'),
        migrations.RemoveField(model_name='googleaccount', name='refresh_token'),
        migrations.RemoveField(model_name='googleaccount', name='token_expiry'),
    ]
