# Generated by Django 6.1 on 2026-08-25 23:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0011_require_private_state_owners'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('course_id', models.CharField(db_index=True, max_length=64)),
                ('original_filename', models.CharField(max_length=255)),
                ('material_type', models.CharField(choices=[('syllabus', 'Syllabus'), ('notes', 'Notes'), ('slides', 'Slides'), ('reference', 'Reference')], max_length=16)),
                ('source_key', models.CharField(blank=True, max_length=64)),
                ('source_date', models.CharField(blank=True, max_length=10, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processing_status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('needs_review', 'Needs review'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('failure_message', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('not_required', 'Not required'), ('superseded', 'Superseded')], default='pending', max_length=20)),
                ('storage_key', models.CharField(max_length=96)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'course_id', 'uploaded_at'], name='agent_mater_user_course_idx'), models.Index(fields=['user', 'processing_status'], name='agent_mater_user_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'course_id', 'storage_key'), name='unique_material_storage_key')],
            },
        ),
    ]
