# Generated by Django 6.1 on 2026-08-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0012_course_material_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesession',
            name='title',
            field=models.CharField(default='New chat', max_length=255),
        ),
        migrations.AddField(
            model_name='sessionmessage',
            name='client_request_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='sessionmessage',
            name='response_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddConstraint(
            model_name='sessionmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', False)), fields=('session', 'client_request_id'), name='unique_session_client_request'),
        ),
    ]
