# Generated by Django 6.1 on 2026-08-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0013_cora_citations_and_conversations'),
    ]

    operations = [
        migrations.AddField(
            model_name='customevent',
            name='estimated_effort_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customevent',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('study_plan', 'Study plan')], default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='customevent',
            name='source_material_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
