# Generated by Django 6.1 on 2026-08-26 02:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0014_customevent_estimated_effort_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardprogress',
            name='interval_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashcardprogress',
            name='last_reviewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flashcardprogress',
            name='next_review',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flashcardprogress',
            name='rating',
            field=models.CharField(blank=True, choices=[('again', 'Again'), ('hard', 'Hard'), ('good', 'Good'), ('easy', 'Easy')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='flashcardprogress',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashcardprogress',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('course_id', models.CharField(db_index=True, max_length=64)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('mixed', 'Mixed'), ('flashcards', 'Flashcards only'), ('quiz', 'Quiz only')], default='mixed', max_length=16)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('session_started', 'Session started'), ('flashcard_reviewed', 'Flashcard reviewed'), ('quiz_answered', 'Quiz answered'), ('session_completed', 'Session completed')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='agent.studysession')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'course_id', 'started_at'], name='agent_studysess_usr_crs_idx'),
        ),
        migrations.AddConstraint(
            model_name='studyactivity',
            constraint=models.UniqueConstraint(fields=('session', 'position'), name='unique_study_activity_position'),
        ),
    ]
