# Generated by Django 6.1 on 2026-08-26 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0016_mastery_v2_and_recommendations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, max_length=64)),
                ('event_id', models.CharField(db_index=True, max_length=128)),
                ('included_topics', models.JSONField(blank=True, default=list)),
                ('included_material_ids', models.JSONField(blank=True, default=list)),
                ('study_guide', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'course_id'], name='agent_examplan_user_course_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'event_id'), name='unique_exam_plan_per_event')],
            },
        ),
    ]
