# Generated by Django 6.1 on 2026-09-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0026_usersettings_email_notifications_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='access_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='cohort',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='tier',
            field=models.CharField(choices=[('pilot', 'Pilot'), ('full', 'Full')], default='pilot', max_length=16),
        ),
    ]
