# Generated by Django 6.1 on 2026-09-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0028_backfill_access_status_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecalendarconnection',
            name='grant_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
