# Generated by Django 6.1 on 2026-09-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0031_usersettings_academic_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customevent',
            name='series_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
