# Generated by Django 6.1 on 2026-09-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0032_customevent_series_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmusage',
            name='tokens',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
