# Generated by Django 6.1 on 2026-09-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0033_llmusage_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty')], db_index=True, default='student', max_length=16),
        ),
    ]
