# Generated by Django 6.1 on 2026-09-25 00:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0034_add_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('program_name', models.CharField(blank=True, default='', max_length=200)),
                ('catalog_year', models.CharField(blank=True, default='', max_length=20)),
                ('requirements', models.JSONField()),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_requirements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'program_name', 'catalog_year'), name='unique_program_requirement')],
            },
        ),
    ]
