from django.urls import path

from . import views

urlpatterns = [
    path("profile/", views.UserProfileView.as_view(), name="profile"),
    path("profile/export/", views.AccountExportView.as_view(), name="profile-export"),
    path("courses/overview/", views.CoursesOverviewView.as_view(), name="courses-overview"),
    # slug converter ([-a-zA-Z0-9_]+) rejects "/" and ".." in course_id at the
    # routing layer, before it can reach storage.py as a path segment.
    path("courses/<slug:course_id>/header/", views.CourseHeaderView.as_view(), name="course-header"),
    path("courses/<slug:course_id>/overview/", views.CourseOverviewView.as_view(), name="course-overview"),
    path("courses/<slug:course_id>/syllabus/extract/", views.ExtractSyllabusView.as_view(), name="extract-syllabus"),
    path("courses/<slug:course_id>/syllabus/", views.SyllabusDetailView.as_view(), name="syllabus-detail"),
    path("courses/<slug:course_id>/notes/chunk/", views.ChunkNotesView.as_view(), name="chunk-notes"),
    path("courses/<slug:course_id>/references/", views.ReferencesView.as_view(), name="references"),
    path("courses/<slug:course_id>/materials/", views.CourseMaterialsView.as_view(), name="materials-list"),
    path(
        "courses/<slug:course_id>/materials/<uuid:material_id>/",
        views.CourseMaterialDetailView.as_view(),
        name="material-detail",
    ),
    path(
        "courses/<slug:course_id>/materials/<uuid:material_id>/confirm/",
        views.SyllabusReviewView.as_view(),
        name="material-confirm",
    ),
    path(
        "courses/<slug:course_id>/materials/<uuid:material_id>/retry/",
        views.MaterialRetryView.as_view(),
        name="material-retry",
    ),
    path(
        "courses/<slug:course_id>/materials/<uuid:material_id>/download/",
        views.MaterialDownloadView.as_view(),
        name="material-download",
    ),
    path("courses/<slug:course_id>/saved-sites/", views.SavedSitesView.as_view(), name="saved-sites"),
    path("courses/<slug:course_id>/domains/suggest/", views.DomainSuggestionsView.as_view(), name="domains-suggest"),
    path("courses/<slug:course_id>/domains/", views.DomainsView.as_view(), name="domains"),
    path("courses/<slug:course_id>/grading/", views.GradingConfigView.as_view(), name="grading-config"),
    path("courses/<slug:course_id>/calendar-sync/", views.CalendarSyncView.as_view(), name="calendar-sync"),
    path("courses/<slug:course_id>/archive/", views.CourseArchiveView.as_view(), name="course-archive"),
    path("courses/<slug:course_id>/grades/", views.GradesView.as_view(), name="grades-detail"),
    path("courses/<slug:course_id>/grades/items/", views.GradeItemsView.as_view(), name="grade-items"),
    path("courses/<slug:course_id>/grades/items/<str:item_id>/", views.GradeItemDetailView.as_view(), name="grade-item-detail"),
    path("courses/<slug:course_id>/grades/whatif/", views.GradesWhatIfView.as_view(), name="grades-whatif"),
    path("courses/<slug:course_id>/grades/project/", views.GradeProjectionView.as_view(), name="grades-project"),
    path("courses/<slug:course_id>/exams/", views.ExamsListView.as_view(), name="exams-list"),
    path("courses/<slug:course_id>/exams/<str:event_id>/", views.ExamWorkspaceView.as_view(), name="exam-workspace"),
    path("courses/<slug:course_id>/exams/<str:event_id>/plan/", views.ExamPlanView.as_view(), name="exam-plan"),
    path(
        "courses/<slug:course_id>/exams/<str:event_id>/study-guide/",
        views.ExamStudyGuideView.as_view(),
        name="exam-study-guide",
    ),
    path("courses/<slug:course_id>/mastery/", views.MasteryView.as_view(), name="mastery"),
    path("courses/<slug:course_id>/mastery/rebuild/", views.MasteryRebuildView.as_view(), name="mastery-rebuild"),
    path("courses/<slug:course_id>/flashcards/generate/", views.FlashcardsGenerateView.as_view(), name="flashcards-generate"),
    path("courses/<slug:course_id>/flashcards/progress/", views.FlashcardProgressView.as_view(), name="flashcards-progress"),
    path("courses/<slug:course_id>/flashcards/progress/reset/", views.FlashcardProgressResetView.as_view(), name="flashcards-progress-reset"),
    path("courses/<slug:course_id>/flashcards/review/", views.FlashcardReviewView.as_view(), name="flashcards-review"),
    path("courses/<slug:course_id>/flashcards/suspend/", views.FlashcardSuspendView.as_view(), name="flashcards-suspend"),
    path("courses/<slug:course_id>/flashcards/due/", views.FlashcardsDueView.as_view(), name="flashcards-due"),
    path("courses/<slug:course_id>/quiz/generate/", views.QuizGenerateView.as_view(), name="quiz-generate"),
    path("courses/<slug:course_id>/quiz/record/", views.QuizRecordView.as_view(), name="quiz-record"),
    path("courses/<slug:course_id>/quiz/history/", views.QuizHistoryView.as_view(), name="quiz-history"),
    path("courses/<slug:course_id>/study/quizzes/<str:quiz_id>/attempts/", views.PracticeAttemptsView.as_view(), name="practice-attempts"),
    path("courses/<slug:course_id>/study/quizzes/attempts/<uuid:attempt_id>/", views.PracticeAttemptDetailView.as_view(), name="practice-attempt-detail"),
    path("courses/<slug:course_id>/study/quizzes/attempts/<uuid:attempt_id>/finalize/", views.PracticeAttemptFinalizeView.as_view(), name="practice-attempt-finalize"),
    path("courses/<slug:course_id>/study/flashcards/<slug:deck_id>/sessions/", views.InteractiveFlashcardSessionsView.as_view(), name="interactive-flashcard-sessions"),
    path("courses/<slug:course_id>/study/flashcards/sessions/<uuid:session_id>/", views.InteractiveFlashcardDetailView.as_view(), name="interactive-flashcard-detail"),
    path("courses/<slug:course_id>/study/flashcards/sessions/<uuid:session_id>/reveal/", views.InteractiveFlashcardRevealView.as_view(), name="interactive-flashcard-reveal"),
    path("courses/<slug:course_id>/study/flashcards/sessions/<uuid:session_id>/rate/", views.InteractiveFlashcardRateView.as_view(), name="interactive-flashcard-rate"),
    path("courses/<slug:course_id>/study/flashcards/sessions/<uuid:session_id>/end/", views.InteractiveFlashcardEndView.as_view(), name="interactive-flashcard-end"),
    path("courses/<slug:course_id>/study/sessions/", views.StudySessionsView.as_view(), name="study-sessions"),
    path("courses/<slug:course_id>/study/plan/", views.GuidedStudyPlanView.as_view(), name="guided-study-plan"),
    path(
        "courses/<slug:course_id>/study/sessions/<uuid:session_id>/",
        views.StudySessionDetailView.as_view(),
        name="study-session-detail",
    ),
    path(
        "courses/<slug:course_id>/study/sessions/<uuid:session_id>/activities/",
        views.StudySessionActivityView.as_view(),
        name="study-session-activities",
    ),
    path(
        "courses/<slug:course_id>/study/sessions/<uuid:session_id>/complete/",
        views.StudySessionCompleteView.as_view(),
        name="study-session-complete",
    ),
    path("courses/<slug:course_id>/ask/", views.AskView.as_view(), name="ask-course"),
    path(
        "courses/<slug:course_id>/sessions/<slug:session_id>/deadlines/confirm/",
        views.ConfirmDeadlineActionsView.as_view(),
        name="confirm-deadline-actions",
    ),
    path("courses/<slug:course_id>/sources/preview/", views.SourcePreviewView.as_view(), name="source-preview"),
    path("courses/<slug:course_id>/sessions/", views.SessionsView.as_view(), name="sessions-list-create"),
    path(
        "courses/<slug:course_id>/sessions/<slug:session_id>/",
        views.SessionDetailView.as_view(),
        name="session-detail",
    ),
    path("courses/<slug:course_id>/", views.CourseView.as_view(), name="course-detail"),
    path("reminders/", views.RemindersView.as_view(), name="reminders"),
    path("dashboard/", views.DashboardView.as_view(), name="dashboard"),
    path("recommendations/", views.RecommendationsView.as_view(), name="recommendations"),
    path("recommendations/dismiss/", views.RecommendationDismissView.as_view(), name="recommendations-dismiss"),
    path("grades/summary/", views.GradesSummaryView.as_view(), name="grades-summary"),
    path("deadlines/", views.DeadlinesView.as_view(), name="deadlines"),
    path("calendar/", views.CalendarView.as_view(), name="calendar-data"),
    path("deadlines/<str:event_id>/", views.CustomEventDetailView.as_view(), name="custom-event-detail"),
    path("deadlines/<str:event_id>/calendar-sync/", views.CustomEventCalendarSyncView.as_view(), name="custom-event-calendar-sync"),
    path("notifications/", views.NotificationsView.as_view(), name="notifications"),
    path("notifications/read/", views.NotificationsReadView.as_view(), name="notifications-read"),
]
